<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Client extends \App\Entity\Client implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'account' => [parent::class, 'account', null],
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null],
        "\0".parent::class."\0".'detteRequests' => [parent::class, 'detteRequests', null],
        "\0".parent::class."\0".'dettes' => [parent::class, 'dettes', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'surname' => [parent::class, 'surname', null],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null],
        'account' => [parent::class, 'account', null],
        'adresse' => [parent::class, 'adresse', null],
        'detteRequests' => [parent::class, 'detteRequests', null],
        'dettes' => [parent::class, 'dettes', null],
        'id' => [parent::class, 'id', null],
        'surname' => [parent::class, 'surname', null],
        'telephone' => [parent::class, 'telephone', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
