<?php

namespace ContainerCRtvsOa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9mM_OibService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9mM.Oib' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9mM.Oib'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\ArticleController::index' => ['privates', '.service_locator.IqSceiR.App\\Controller\\ArticleController::index()', 'getArticleControllerindexService', true],
            'App\\Controller\\ArticleController::new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ArticleController::new()', 'getArticleControllernewService', true],
            'App\\Controller\\ArticleController::show' => ['privates', '.service_locator.mBZG5U8.App\\Controller\\ArticleController::show()', 'getArticleControllershowService', true],
            'App\\Controller\\ArticleController::edit' => ['privates', '.service_locator.AazXZCq.App\\Controller\\ArticleController::edit()', 'getArticleControllereditService', true],
            'App\\Controller\\ArticleController::delete' => ['privates', '.service_locator.AazXZCq.App\\Controller\\ArticleController::delete()', 'getArticleControllerdeleteService', true],
            'App\\Controller\\ArticleController::updateStock' => ['privates', '.service_locator.AazXZCq.App\\Controller\\ArticleController::updateStock()', 'getArticleControllerupdateStockService', true],
            'App\\Controller\\ClientController::new' => ['privates', '.service_locator.FLHeY_M.App\\Controller\\ClientController::new()', 'getClientControllernewService', true],
            'App\\Controller\\ClientController::getDettesByClient' => ['privates', '.service_locator.bSaFovV.App\\Controller\\ClientController::getDettesByClient()', 'getClientControllergetDettesByClientService', true],
            'App\\Controller\\DetteController::index' => ['privates', '.service_locator.AjxBq8..App\\Controller\\DetteController::index()', 'getDetteControllerindexService', true],
            'App\\Controller\\DetteController::makePayment' => ['privates', '.service_locator.CKzXXGR.App\\Controller\\DetteController::makePayment()', 'getDetteControllermakePaymentService', true],
            'App\\Controller\\DetteController::makePaymentClient' => ['privates', '.service_locator.CKzXXGR.App\\Controller\\DetteController::makePaymentClient()', 'getDetteControllermakePaymentClientService', true],
            'App\\Controller\\DetteController::new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\DetteController::new()', 'getDetteControllernewService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\TestContollerController::testPassword' => ['privates', '.service_locator.k6tyeIK', 'get_ServiceLocator_K6tyeIKService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.bTA9FKH.App\\Controller\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.__CzQUd.App\\Controller\\UserController::new()', 'getUserControllernewService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.hKA2je_.App\\Controller\\UserController::show()', 'getUserControllershowService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.Qh67eS1.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.nLtHlEw.App\\Controller\\UserController::delete()', 'getUserControllerdeleteService', true],
            'App\\Controller\\UserController::toggleActive' => ['privates', '.service_locator.nLtHlEw.App\\Controller\\UserController::toggleActive()', 'getUserControllertoggleActiveService', true],
            'App\\Controller\\UserController::filter' => ['privates', '.service_locator.bTA9FKH.App\\Controller\\UserController::filter()', 'getUserControllerfilterService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\ArticleController:index' => ['privates', '.service_locator.IqSceiR.App\\Controller\\ArticleController::index()', 'getArticleControllerindexService', true],
            'App\\Controller\\ArticleController:new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ArticleController::new()', 'getArticleControllernewService', true],
            'App\\Controller\\ArticleController:show' => ['privates', '.service_locator.mBZG5U8.App\\Controller\\ArticleController::show()', 'getArticleControllershowService', true],
            'App\\Controller\\ArticleController:edit' => ['privates', '.service_locator.AazXZCq.App\\Controller\\ArticleController::edit()', 'getArticleControllereditService', true],
            'App\\Controller\\ArticleController:delete' => ['privates', '.service_locator.AazXZCq.App\\Controller\\ArticleController::delete()', 'getArticleControllerdeleteService', true],
            'App\\Controller\\ArticleController:updateStock' => ['privates', '.service_locator.AazXZCq.App\\Controller\\ArticleController::updateStock()', 'getArticleControllerupdateStockService', true],
            'App\\Controller\\ClientController:new' => ['privates', '.service_locator.FLHeY_M.App\\Controller\\ClientController::new()', 'getClientControllernewService', true],
            'App\\Controller\\ClientController:getDettesByClient' => ['privates', '.service_locator.bSaFovV.App\\Controller\\ClientController::getDettesByClient()', 'getClientControllergetDettesByClientService', true],
            'App\\Controller\\DetteController:index' => ['privates', '.service_locator.AjxBq8..App\\Controller\\DetteController::index()', 'getDetteControllerindexService', true],
            'App\\Controller\\DetteController:makePayment' => ['privates', '.service_locator.CKzXXGR.App\\Controller\\DetteController::makePayment()', 'getDetteControllermakePaymentService', true],
            'App\\Controller\\DetteController:makePaymentClient' => ['privates', '.service_locator.CKzXXGR.App\\Controller\\DetteController::makePaymentClient()', 'getDetteControllermakePaymentClientService', true],
            'App\\Controller\\DetteController:new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\DetteController::new()', 'getDetteControllernewService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\TestContollerController:testPassword' => ['privates', '.service_locator.k6tyeIK', 'get_ServiceLocator_K6tyeIKService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.bTA9FKH.App\\Controller\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.__CzQUd.App\\Controller\\UserController::new()', 'getUserControllernewService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.hKA2je_.App\\Controller\\UserController::show()', 'getUserControllershowService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.Qh67eS1.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.nLtHlEw.App\\Controller\\UserController::delete()', 'getUserControllerdeleteService', true],
            'App\\Controller\\UserController:toggleActive' => ['privates', '.service_locator.nLtHlEw.App\\Controller\\UserController::toggleActive()', 'getUserControllertoggleActiveService', true],
            'App\\Controller\\UserController:filter' => ['privates', '.service_locator.bTA9FKH.App\\Controller\\UserController::filter()', 'getUserControllerfilterService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ArticleController::index' => '?',
            'App\\Controller\\ArticleController::new' => '?',
            'App\\Controller\\ArticleController::show' => '?',
            'App\\Controller\\ArticleController::edit' => '?',
            'App\\Controller\\ArticleController::delete' => '?',
            'App\\Controller\\ArticleController::updateStock' => '?',
            'App\\Controller\\ClientController::new' => '?',
            'App\\Controller\\ClientController::getDettesByClient' => '?',
            'App\\Controller\\DetteController::index' => '?',
            'App\\Controller\\DetteController::makePayment' => '?',
            'App\\Controller\\DetteController::makePaymentClient' => '?',
            'App\\Controller\\DetteController::new' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\TestContollerController::testPassword' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::toggleActive' => '?',
            'App\\Controller\\UserController::filter' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ArticleController:index' => '?',
            'App\\Controller\\ArticleController:new' => '?',
            'App\\Controller\\ArticleController:show' => '?',
            'App\\Controller\\ArticleController:edit' => '?',
            'App\\Controller\\ArticleController:delete' => '?',
            'App\\Controller\\ArticleController:updateStock' => '?',
            'App\\Controller\\ClientController:new' => '?',
            'App\\Controller\\ClientController:getDettesByClient' => '?',
            'App\\Controller\\DetteController:index' => '?',
            'App\\Controller\\DetteController:makePayment' => '?',
            'App\\Controller\\DetteController:makePaymentClient' => '?',
            'App\\Controller\\DetteController:new' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\TestContollerController:testPassword' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:show' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:toggleActive' => '?',
            'App\\Controller\\UserController:filter' => '?',
        ]);
    }
}
