<?php

namespace ContainerCRtvsOa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDetteControllermakePaymentClientService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CKzXXGR.App\Controller\DetteController::makePaymentClient()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CKzXXGR.App\\Controller\\DetteController::makePaymentClient()'] = ($container->privates['.service_locator.CKzXXGR'] ?? $container->load('get_ServiceLocator_CKzXXGRService'))->withContext('App\\Controller\\DetteController::makePaymentClient()', $container);
    }
}
