<?php

namespace ContainerHQuHQ5C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CKzXXGRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CKzXXGR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CKzXXGR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dette' => ['privates', '.errored..service_locator.CKzXXGR.App\\Entity\\Dette', NULL, 'Cannot autowire service ".service_locator.CKzXXGR": it needs an instance of "App\\Entity\\Dette" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'dette' => 'App\\Entity\\Dette',
            'entityManager' => '?',
        ]);
    }
}
