<?php

namespace ContainerHQuHQ5C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientFormComponentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Twig\Components\ClientFormComponent' autowired service.
     *
     * @return \App\Twig\Components\ClientFormComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/ComponentWithFormTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/DefaultActionTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Twig/Components/ClientFormComponent.php';

        $container->factories['App\\Twig\\Components\\ClientFormComponent'] = function ($container) {
            $instance = new \App\Twig\Components\ClientFormComponent();

            $instance->setContainer(($container->privates['.service_locator.QaaoWjx.App\\Twig\\Components\\ClientFormComponent'] ?? $container->load('getClientFormComponent2Service')));

            return $instance;
        };

        return $container->factories['App\\Twig\\Components\\ClientFormComponent']($container);
    }
}
