<?php

namespace ContainerHQuHQ5C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientFormComponent2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QaaoWjx.App\Twig\Components\ClientFormComponent' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'));

        if (isset($container->privates['.service_locator.QaaoWjx.App\\Twig\\Components\\ClientFormComponent'])) {
            return $container->privates['.service_locator.QaaoWjx.App\\Twig\\Components\\ClientFormComponent'];
        }

        return $container->privates['.service_locator.QaaoWjx.App\\Twig\\Components\\ClientFormComponent'] = $a->withContext('App\\Twig\\Components\\ClientFormComponent', $container);
    }
}
