<?php

namespace ContainerHQuHQ5C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDetteControllermakePaymentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CKzXXGR.App\Controller\DetteController::makePayment()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.CKzXXGR'] ?? $container->load('get_ServiceLocator_CKzXXGRService'));

        if (isset($container->privates['.service_locator.CKzXXGR.App\\Controller\\DetteController::makePayment()'])) {
            return $container->privates['.service_locator.CKzXXGR.App\\Controller\\DetteController::makePayment()'];
        }

        return $container->privates['.service_locator.CKzXXGR.App\\Controller\\DetteController::makePayment()'] = $a->withContext('App\\Controller\\DetteController::makePayment()', $container);
    }
}
