<?php

namespace ContainerHQuHQ5C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNavigationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Twig\Components\Navigation' autowired service.
     *
     * @return \App\Twig\Components\Navigation
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Twig/Components/Navigation.php';

        $container->factories['service_container']['App\\Twig\\Components\\Navigation'] = function ($container) {
            return new \App\Twig\Components\Navigation();
        };

        return $container->factories['service_container']['App\\Twig\\Components\\Navigation']($container);
    }
}
