<?php

namespace ContainerHQuHQ5C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestContollerControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\TestContollerController' shared autowired service.
     *
     * @return \App\Controller\TestContollerController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/TestContollerController.php';

        $container->services['App\\Controller\\TestContollerController'] = $instance = new \App\Controller\TestContollerController();

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\TestContollerController', $container));

        return $instance;
    }
}
