<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHQuHQ5C\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHQuHQ5C/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHQuHQ5C.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHQuHQ5C\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHQuHQ5C\App_KernelDevDebugContainer([
    'container.build_hash' => 'HQuHQ5C',
    'container.build_id' => '15e74e1c',
    'container.build_time' => 1734628497,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHQuHQ5C');
