<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.8ab7f0c8.js',
                '/build/298.571acf36.js',
                '/build/app.7697c39d.js',
            ],
            'css' => [
                '/build/app.025c1f23.css',
            ],
        ],
    ],
],

]];
